@startuml
    abstract class ActiveRecord{
        {abstract} +Leer(): Boolean
        {abstract} +Insertar(): Boolean
        {abstract} +Actualizar(): Boolean
        {abstract} +Eliminar(): Boolean
    }
@enduml