@startuml Pais
!include ActiveRecord.plantuml

namespace Haberes {

Class Pais extends Datos.ActiveRecord{
    +pai_id: int
    +pai_nombre: String
    +pai_nacionalidad: String
    +pai_vigente: boolean
}


}




@enduml